lint:
	black ./Jingyao_Du/test_game_of_life.py
	isort ./Jingyao_Du/test_game_of_life.py
	flake8 ./Jingyao_Du/test_game_of_life.py

lint-check:
	black . --check
	isort . --check
	flake8 .

test:
	pytest .
